word = input("hi i am a paladrome detector please put a frase in or a word and i will tell you if it's a palodrome or not: ")

a = (word.find("a"),1)
b = (word.find("b"),2)
c = (word.find("c"),3)
d = (word.find("d"),4)
e = (word.find("e"),5)
f = (word.find("f"),6)
g = (word.find("g"),7)
h = (word.find("h"),8)
i = (word.find("i"),9)
j = (word.find("j"),10)
k = (word.find("k"),11)
l = (word.find("l"),12)
m = (word.find("m"),13)
n = (word.find("n"),14)
o = (word.find("o"),15)
p = (word.find("p"),16)
q = (word.find("q"),17)
r = (word.find("r"),18)
s = (word.find("s"),19)
t = (word.find("t"),20)
u = (word.find("u"),21)
v = (word.find("v"),22)
w = (word.find("w"),23)
x = (word.find("x"),24)
y = (word.find("y"),25)
z = (word.find("z"),26)
aa = (word.find("A"),27)
bb = (word.find("B"),28)
cc = (word.find("C"),29)
dd = (word.find("D"),30)
ee = (word.find("E"),31)
ff = (word.find("F"),32)
gg = (word.find("G"),33)
hh = (word.find("H"),34)
ii = (word.find("I"),35)
jj = (word.find("J"),36)
kk = (word.find("K"),37)
ll = (word.find("L"),38)
mm = (word.find("M"),39)
nn = (word.find("N"),40)
oo = (word.find("O"),41)
pp = (word.find("P"),42)
qq = (word.find("Q"),43)
rr = (word.find("R"),44)
ss = (word.find("S"),45)
tt = (word.find("T"),46)
uu = (word.find("U"),47)
vv = (word.find("V"),48)
ww = (word.find("W"),49)
xx = (word.find("X"),50)
yy = (word.find("Y"),51)
zz = (word.find("Z"),52)
spacebar = (word.find(" "),53)
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(i)
print(j)
print(k)
print(l)
print(m)
print(n)
print(o)
print(p)
print(q)
print(r)
print(s)
print(t)
print(u)
print(v)
print(w)
print(x)
print(y)
print(z)
print(aa)
print(bb)
print(cc)
print(dd)
print(ee)
print(ff)
print(gg)
print(hh)
print(ii)
print(jj)
print(kk)
print(ll)
print(mm)
print(oo)
print(pp)
print(qq)
print(rr)
print(ss)
print(tt)
print(uu)
print(vv)
print(ww)
print(xx)
print(yy)
print(zz)
print(spacebar)
