var=1
if var==1:
	if var==1:
		if var==1:
			if var==1:
				if var==1:
					if var==1:
						if var==1:
							if var==1:
								if var==1:
									if var==1:
										if var==1:
											if var==1:
												if var==1:
													if var==1:
														if var==1:
															if var==1:
																if var==1:
																	if var==1:
																		if var==1:
																			if var==1:
																				if var==1:
																					if var==1:
																						if var==1:
																							if var==1:
																								if var==1:
																									if var==1:
																										if var==1:
																											if var==1:
																												if var==1:
																													if var==1:
																														if var==1:
																															if var==1:
																																if var==1:
																																	if var==1:
																																		if var==1:
																																			if var==1:
																																				if var==1:
																																					if var==1:
																																						if var==1:
																																							if var==1:
																																								if var==1:
																																									if var==1:
																																										if var==1:
																																											if var==1:
																																												if var==1:
																																													if var==1:
																																														if var==1:
																																															if var==1:
																																																if var==1:
																																																	if var==1:
																																																		if var==1:
																																																			if var==1:
																																																				if var==1:
																																																					if var==1:
																																																						if var==1:
																																																							if var==1:
																																																								if var==1:
																																																									if var==1:
																																																										if var==1:
																																																											if var==1:
																																																												if var==1:
																																																													if var==1:
																																																														if var==1:
																																																															if var==1:
																																																																if var==1:
																																																																	if var==1:
																																																																		if var==1:
																																																																			if var==1:
																																																																				if var==1:
																																																																					if var==1:
																																																																						if var==1:
																																																																							if var==1:
																																																																								if var==1:
																																																																									if var==1:
																																																																										if var==1:
																																																																											if var==1:
																																																																												if var==1:
																																																																													if var==1:
																																																																														if var==1:
																																																																															if var==1:
																																																																																if var==1:
																																																																																	if var==1:
																																																																																		if var==1:
																																																																																			if var==1:
																																																																																				if var==1:
																																																																																					if var==1:
																																																																																						if var==1:
																																																																																							if var==1:
																																																																																								if var==1:
																																																																																									if var==1:
																																																																																										if var==1:
																																																																																											if var==1:
																																																																																												if var==1:
																																																																																													if var==1:
																																																																																														if var==1:
																																																																																															if var==1:
																																																																																																if var==1:
																																																																																																	if var==1:
																																																																																																		if var==1:
																																																																																																			print("the variable DEFANITLY is equal to 1")